folder_path = [pwd,'\PhMatlabSDK'];
addpath(pwd,folder_path, ...
    [folder_path,'\Bin'],...         %   [folder_path,'Bin\win32']
    [folder_path,'\Bin\x64'],...
    [folder_path,'\Doc'],...
    [folder_path,'\Doc\Phantom SDK Doc'],...
    [folder_path,'\PhDemoMatlab'],...
    [folder_path,'\PhDemoMatlab\CamInfoDlg'],...
    [folder_path,'\PhMatlab'],...
    [folder_path,'\PhMatlab\Constants'],...
    [folder_path,'\PhMatlab\Inc'],...
    [folder_path,'\PhMatlab\OOP'],...
    [folder_path,'\PhMatlab\Other'],...
    [folder_path,'\PhMatlab\Other\Utils'],...
    [folder_path,'\PhMatlab\PhCon'],...
    [folder_path,'\PhMatlab\PhFile'],...
    [folder_path,'\PhMatlab\PhInt'],...
    [folder_path,'\SimpleCineFileReader']);